### ISSUE TITLE
[react_roles] bot removing the highest role of users

### ISSUE THREAD

**Issue by thisisjvgrace** [ZeLarpMaster/ZeCogsV3#19]
Hi , 

as we recently discussed in #support_othercogs, I am having this bug with react_roles cog, not sure if I should call it a bug or not but I will try to explain it as briefly as I can, so in my server, new joining members first arrive in #initiation channel where once they type "I agree to the rules", they are given "Boar Hat Customer" role (lets call it BHC for convenience here) and this role gives them access to rest of the server. Now in a separate channel #clan-roles, I have setup your react_roles and setup 7 clan roles (Demon, Druids, Fairy, Giant, Human, Goddess, Vampire). These set reaction roles are exclusive to each other, meaning, any member will only be allowed to have either one of 7 clan roles at any given point of time.

The role hierarchy is such that BHC role is on top of these 7 clan roles, and bot's role is above these all roles.
But when a member clicks on all 7 reactions in a fast manner, the bot removes the member's top role , which is BHC in this case. and without BHC role, that existing approved member of guild gets pushed back to #initiation channel because of how the BHC role is set up in channel permissions because of verification purposes. and BHC role is not setup in any of those reaction roles , I have confirmed this thoroughly, so I am puzzled as why it's removing users' top BHC role. although this happened rarely, (3 out of last 50 new joins), all 3 of them tapped on reactions fast from what they told me, but I thought I would let you know. I am on RC2 V3 latest. ^^

**Comment by Zewb** [comment]
I'm adding to this as it might be a related issue or a totally separate but similar issue.  The issue I have is that when the person is given a role not bound to a reaction, (eg; manually by an admin/mod or the old bot before our switch) as soon as they add a reaction role they lose all other roles that aren't assigned by a reaction.  My pondering was if the bot does a check on reactions and roles and updates when someone requests a new role, deleting any roles not tied to a reaction.  

I have temporarily hoisted the hidden roles above the bot so that it can no longer remove them but was curious if there was an expectation for it to have this behavior or if it s a bug related to the former issue that thisisjvgrace has posted.

**Comment by ZeLarpMaster** [comment]
I'm thinking this is an issue with how the guild members are stored and updated. I'll probably just change how the bot adds/removes roles by doing separate calls to `add_roles` and `remove_roles` instead of a single call to `replace_roles`. This should fix these issues.

**Comment by ZeLarpMaster** [comment]
As I've mentioned in #20, this might be fixed by the latest update.

Please update the cog, try again and tell me if this is fixed.

**Comment by Zewb** [comment]
Updated and so far seems to be working just fine. Read your other connect so I'll give a look later and see if and how much it may have slowed down due to the changes.  Thanks for the bug fix.

**Comment by ZeLarpMaster** [comment]
Haven't heard back on it, I'll assume it worked fine.
