### ISSUE TITLE
[react_roles] Not giving roles, reload fixes it

### ISSUE THREAD

**Issue by SevereMatrex** [ZeLarpMaster/ZeCogsV3#20]
React roles using a message cache in that manner may cause some issues. (Specifically, a potential de-sync from the copy you have.) I’d advise using the data the raw events give you to avoid ever needing the actual message object.

Your cogs should use the i18n decorator. Right now none of your cogs work properly with localization, despite having translations, and jumping through a bunch of unnecessary hoops around this. (such as the reload translations portion in each cog)

**Comment by ZeLarpMaster** [comment]
I did changes regarding these two things. Please update the cog and tell me if the issue if fixed.

Please note this also includes a massive performance downgrade because I had to remove the message cache. Roles may take very long before being removed after clicking a reaction, this is especially true if there are links in the affected message and is linearly worse with the number of reactions in linked messages.

As an example, a message containing 10 reactions and a link on it would take about 3 seconds just to add a single role from a single person without having anyone else adding roles at that time. This is 100% due to the removal of the message cache. I unfortunately can't do anything to make this better because of limitations from the Discord API.

This gets worse if multiple people are adding roles or removing roles at the same time. This can very easily take longer for the bot to go through role additions/removals than people are adding/removing roles. This means the bot would never go through everything and it would take longer and longer for new people to gain their roles.

I don't know what I can do about this performance hit. I'll probably look into this again later.

**Note**: This should also fix issues I've seen about the bot removing unrelated roles (see #19)

**Comment by ZeLarpMaster** [comment]
I did another change to remove the performance hit mentioned above.

This may have re-introduced the initial symptoms of the problem, but hopefully not. The issues mentioned above were still fixed so I'll close this issue. If the symptoms reappear, it's likely a different cause so I prefer getting a new issue about it if it does happen.
